name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      generateReport:
        description: "Generate Mochawesome Report"
        type: boolean
        default: false
        required: true
      recordVideo:
        description: "Record Test Videos"
        type: boolean
        default: false
        required: true
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      # Set video configuration based on input
      - name: Configure Cypress Video Recording
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.recordVideo }}" == "true" ]]; then
            echo "Setting video to true in cypress.config.ts"
            sed -i 's/video: false/video: true/' cypress.config.ts
          else
            echo "Setting video to false in cypress.config.ts"
            sed -i 's/video: true/video: false/' cypress.config.ts
          fi

      - run: npm run build --if-present
      - run: npm run test:cy

      # Generate report only if requested via workflow_dispatch
      - name: Generate Mochawesome Report
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.generateReport == 'true'
        run: npm run create:report

      # Upload videos based only on input parameter
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.recordVideo == 'true'
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      # Upload reports only if they were generated
      - name: Upload Screenshots and Reports
        uses: actions/upload-artifact@v4
        if: |
          always() && 
          github.event_name == 'workflow_dispatch' && 
          github.event.inputs.generateReport == 'true'
        with:
          name: cypress-evidence
          path: |
            cypress/screenshots
            reports
          if-no-files-found: ignore
